project:
  type: book

book:
  title: "BM214-Workshop-3"
  author: "Norah Jones"
  date: "3/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



