---
webr:
  packages: ["ggplot2", "tidyverse"]
filters:
  - webr
---

# Yeast Growth Experiment

```{r}
#| echo: false
#| warning: false

download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_01/AM_Bay_01_01.csv', 'AM_Bay_01_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_01/AM_Bay_01_02.csv', 'AM_Bay_01_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_01/AM_Bay_01_03.csv', 'AM_Bay_01_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_01/AM_Bay_01_04.csv', 'AM_Bay_01_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_02/AM_Bay_02_01.csv', 'AM_Bay_02_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_02/AM_Bay_02_02.csv', 'AM_Bay_02_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_02/AM_Bay_02_03.csv', 'AM_Bay_02_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_02/AM_Bay_02_04.csv', 'AM_Bay_02_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_03/AM_Bay_03_01.csv', 'AM_Bay_03_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_03/AM_Bay_03_02.csv', 'AM_Bay_03_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_03/AM_Bay_03_03.csv', 'AM_Bay_03_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_03/AM_Bay_03_04.csv', 'AM_Bay_03_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_04/AM_Bay_04_01.csv', 'AM_Bay_04_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_04/AM_Bay_04_02.csv', 'AM_Bay_04_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_04/AM_Bay_04_03.csv', 'AM_Bay_04_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_04/AM_Bay_04_04.csv', 'AM_Bay_04_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_05/AM_Bay_05_01.csv', 'AM_Bay_05_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_05/AM_Bay_05_02.csv', 'AM_Bay_05_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_05/AM_Bay_05_03.csv', 'AM_Bay_05_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_05/AM_Bay_05_04.csv', 'AM_Bay_05_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_06/AM_Bay_06_01.csv', 'AM_Bay_06_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_06/AM_Bay_06_02.csv', 'AM_Bay_06_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_06/AM_Bay_06_03.csv', 'AM_Bay_06_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_06/AM_Bay_06_04.csv', 'AM_Bay_06_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_07/AM_Bay_07_01.csv', 'AM_Bay_07_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_07/AM_Bay_07_02.csv', 'AM_Bay_07_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_07/AM_Bay_07_03.csv', 'AM_Bay_07_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_07/AM_Bay_07_04.csv', 'AM_Bay_07_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_08/AM_Bay_08_01.csv', 'AM_Bay_08_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_08/AM_Bay_08_02.csv', 'AM_Bay_08_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_08/AM_Bay_08_03.csv', 'AM_Bay_08_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_08/AM_Bay_08_04.csv', 'AM_Bay_08_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_09/AM_Bay_09_01.csv', 'AM_Bay_09_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_09/AM_Bay_09_02.csv', 'AM_Bay_09_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_09/AM_Bay_09_03.csv', 'AM_Bay_09_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_09/AM_Bay_09_04.csv', 'AM_Bay_09_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_10/AM_Bay_10_01.csv', 'AM_Bay_10_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_10/AM_Bay_10_02.csv', 'AM_Bay_10_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_10/AM_Bay_10_03.csv', 'AM_Bay_10_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_10/AM_Bay_10_04.csv', 'AM_Bay_10_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_11/AM_Bay_11_01.csv', 'AM_Bay_11_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_11/AM_Bay_11_02.csv', 'AM_Bay_11_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_11/AM_Bay_11_03.csv', 'AM_Bay_11_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_11/AM_Bay_11_04.csv', 'AM_Bay_11_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_12/AM_Bay_12_01.csv', 'AM_Bay_12_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_12/AM_Bay_12_02.csv', 'AM_Bay_12_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_12/AM_Bay_12_03.csv', 'AM_Bay_12_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_12/AM_Bay_12_04.csv', 'AM_Bay_12_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_13/AM_Bay_13_01.csv', 'AM_Bay_13_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_13/AM_Bay_13_02.csv', 'AM_Bay_13_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_13/AM_Bay_13_03.csv', 'AM_Bay_13_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_13/AM_Bay_13_04.csv', 'AM_Bay_13_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_14/AM_Bay_14_01.csv', 'AM_Bay_14_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_14/AM_Bay_14_02.csv', 'AM_Bay_14_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_14/AM_Bay_14_03.csv', 'AM_Bay_14_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_14/AM_Bay_14_04.csv', 'AM_Bay_14_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_15/AM_Bay_15_01.csv', 'AM_Bay_15_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_15/AM_Bay_15_02.csv', 'AM_Bay_15_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_15/AM_Bay_15_03.csv', 'AM_Bay_15_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_15/AM_Bay_15_04.csv', 'AM_Bay_15_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_16/AM_Bay_16_01.csv', 'AM_Bay_16_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_16/AM_Bay_16_02.csv', 'AM_Bay_16_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_16/AM_Bay_16_03.csv', 'AM_Bay_16_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_16/AM_Bay_16_04.csv', 'AM_Bay_16_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_17/AM_Bay_17_01.csv', 'AM_Bay_17_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_17/AM_Bay_17_02.csv', 'AM_Bay_17_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_17/AM_Bay_17_03.csv', 'AM_Bay_17_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_17/AM_Bay_17_04.csv', 'AM_Bay_17_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_18/AM_Bay_18_01.csv', 'AM_Bay_18_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_18/AM_Bay_18_02.csv', 'AM_Bay_18_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_18/AM_Bay_18_03.csv', 'AM_Bay_18_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_18/AM_Bay_18_04.csv', 'AM_Bay_18_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_19/AM_Bay_19_01.csv', 'AM_Bay_19_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_19/AM_Bay_19_02.csv', 'AM_Bay_19_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_19/AM_Bay_19_03.csv', 'AM_Bay_19_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_19/AM_Bay_19_04.csv', 'AM_Bay_19_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_20/AM_Bay_20_01.csv', 'AM_Bay_20_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_20/AM_Bay_20_02.csv', 'AM_Bay_20_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_20/AM_Bay_20_03.csv', 'AM_Bay_20_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_20/AM_Bay_20_04.csv', 'AM_Bay_20_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_21/AM_Bay_21_01.csv', 'AM_Bay_21_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_21/AM_Bay_21_02.csv', 'AM_Bay_21_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_21/AM_Bay_21_03.csv', 'AM_Bay_21_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_21/AM_Bay_21_04.csv', 'AM_Bay_21_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_22/AM_Bay_22_01.csv', 'AM_Bay_22_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_22/AM_Bay_22_02.csv', 'AM_Bay_22_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_22/AM_Bay_22_03.csv', 'AM_Bay_22_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_22/AM_Bay_22_04.csv', 'AM_Bay_22_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_23/AM_Bay_23_01.csv', 'AM_Bay_23_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_23/AM_Bay_23_02.csv', 'AM_Bay_23_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_23/AM_Bay_23_03.csv', 'AM_Bay_23_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_23/AM_Bay_23_04.csv', 'AM_Bay_23_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_24/AM_Bay_24_01.csv', 'AM_Bay_24_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_24/AM_Bay_24_02.csv', 'AM_Bay_24_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_24/AM_Bay_24_03.csv', 'AM_Bay_24_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_24/AM_Bay_24_04.csv', 'AM_Bay_24_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_25/AM_Bay_25_01.csv', 'AM_Bay_25_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_25/AM_Bay_25_02.csv', 'AM_Bay_25_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_25/AM_Bay_25_03.csv', 'AM_Bay_25_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_25/AM_Bay_25_04.csv', 'AM_Bay_25_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_26/AM_Bay_26_01.csv', 'AM_Bay_26_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_26/AM_Bay_26_02.csv', 'AM_Bay_26_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_26/AM_Bay_26_03.csv', 'AM_Bay_26_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_26/AM_Bay_26_04.csv', 'AM_Bay_26_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_27/AM_Bay_27_01.csv', 'AM_Bay_27_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_27/AM_Bay_27_02.csv', 'AM_Bay_27_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_27/AM_Bay_27_03.csv', 'AM_Bay_27_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_27/AM_Bay_27_04.csv', 'AM_Bay_27_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_28/AM_Bay_28_01.csv', 'AM_Bay_28_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_28/AM_Bay_28_02.csv', 'AM_Bay_28_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_28/AM_Bay_28_03.csv', 'AM_Bay_28_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_28/AM_Bay_28_04.csv', 'AM_Bay_28_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_29/AM_Bay_29_01.csv', 'AM_Bay_29_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_29/AM_Bay_29_02.csv', 'AM_Bay_29_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_29/AM_Bay_29_03.csv', 'AM_Bay_29_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_29/AM_Bay_29_04.csv', 'AM_Bay_29_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_30/AM_Bay_30_01.csv', 'AM_Bay_30_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_30/AM_Bay_30_02.csv', 'AM_Bay_30_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_30/AM_Bay_30_03.csv', 'AM_Bay_30_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_30/AM_Bay_30_04.csv', 'AM_Bay_30_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_31/AM_Bay_31_01.csv', 'AM_Bay_31_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_31/AM_Bay_31_02.csv', 'AM_Bay_31_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_31/AM_Bay_31_03.csv', 'AM_Bay_31_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_31/AM_Bay_31_04.csv', 'AM_Bay_31_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_32/AM_Bay_32_01.csv', 'AM_Bay_32_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_32/AM_Bay_32_02.csv', 'AM_Bay_32_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_32/AM_Bay_32_03.csv', 'AM_Bay_32_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_32/AM_Bay_32_04.csv', 'AM_Bay_32_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_33/AM_Bay_33_01.csv', 'AM_Bay_33_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_33/AM_Bay_33_02.csv', 'AM_Bay_33_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_33/AM_Bay_33_03.csv', 'AM_Bay_33_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_33/AM_Bay_33_04.csv', 'AM_Bay_33_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_34/AM_Bay_34_01.csv', 'AM_Bay_34_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_34/AM_Bay_34_02.csv', 'AM_Bay_34_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_34/AM_Bay_34_03.csv', 'AM_Bay_34_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_34/AM_Bay_34_04.csv', 'AM_Bay_34_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_35/AM_Bay_35_01.csv', 'AM_Bay_35_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_35/AM_Bay_35_02.csv', 'AM_Bay_35_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_35/AM_Bay_35_03.csv', 'AM_Bay_35_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_35/AM_Bay_35_04.csv', 'AM_Bay_35_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_36/AM_Bay_36_01.csv', 'AM_Bay_36_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_36/AM_Bay_36_02.csv', 'AM_Bay_36_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_36/AM_Bay_36_03.csv', 'AM_Bay_36_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_36/AM_Bay_36_04.csv', 'AM_Bay_36_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_37/AM_Bay_37_01.csv', 'AM_Bay_37_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_37/AM_Bay_37_02.csv', 'AM_Bay_37_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_37/AM_Bay_37_03.csv', 'AM_Bay_37_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_37/AM_Bay_37_04.csv', 'AM_Bay_37_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_38/AM_Bay_38_01.csv', 'AM_Bay_38_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_38/AM_Bay_38_02.csv', 'AM_Bay_38_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_38/AM_Bay_38_03.csv', 'AM_Bay_38_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_38/AM_Bay_38_04.csv', 'AM_Bay_38_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_39/AM_Bay_39_01.csv', 'AM_Bay_39_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_39/AM_Bay_39_02.csv', 'AM_Bay_39_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_39/AM_Bay_39_03.csv', 'AM_Bay_39_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_39/AM_Bay_39_04.csv', 'AM_Bay_39_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_40/AM_Bay_40_01.csv', 'AM_Bay_40_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_40/AM_Bay_40_02.csv', 'AM_Bay_40_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_40/AM_Bay_40_03.csv', 'AM_Bay_40_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/AM_Bay_40/AM_Bay_40_04.csv', 'AM_Bay_40_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_01/PM_Bay_01_01.csv', 'PM_Bay_01_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_01/PM_Bay_01_02.csv', 'PM_Bay_01_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_01/PM_Bay_01_03.csv', 'PM_Bay_01_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_01/PM_Bay_01_04.csv', 'PM_Bay_01_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_02/PM_Bay_02_01.csv', 'PM_Bay_02_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_02/PM_Bay_02_02.csv', 'PM_Bay_02_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_02/PM_Bay_02_03.csv', 'PM_Bay_02_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_02/PM_Bay_02_04.csv', 'PM_Bay_02_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_03/PM_Bay_03_01.csv', 'PM_Bay_03_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_03/PM_Bay_03_02.csv', 'PM_Bay_03_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_03/PM_Bay_03_03.csv', 'PM_Bay_03_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_03/PM_Bay_03_04.csv', 'PM_Bay_03_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_04/PM_Bay_04_01.csv', 'PM_Bay_04_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_04/PM_Bay_04_02.csv', 'PM_Bay_04_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_04/PM_Bay_04_03.csv', 'PM_Bay_04_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_04/PM_Bay_04_04.csv', 'PM_Bay_04_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_05/PM_Bay_05_01.csv', 'PM_Bay_05_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_05/PM_Bay_05_02.csv', 'PM_Bay_05_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_05/PM_Bay_05_03.csv', 'PM_Bay_05_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_05/PM_Bay_05_04.csv', 'PM_Bay_05_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_06/PM_Bay_06_01.csv', 'PM_Bay_06_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_06/PM_Bay_06_02.csv', 'PM_Bay_06_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_06/PM_Bay_06_03.csv', 'PM_Bay_06_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_06/PM_Bay_06_04.csv', 'PM_Bay_06_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_07/PM_Bay_07_01.csv', 'PM_Bay_07_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_07/PM_Bay_07_02.csv', 'PM_Bay_07_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_07/PM_Bay_07_03.csv', 'PM_Bay_07_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_07/PM_Bay_07_04.csv', 'PM_Bay_07_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_08/PM_Bay_08_01.csv', 'PM_Bay_08_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_08/PM_Bay_08_02.csv', 'PM_Bay_08_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_08/PM_Bay_08_03.csv', 'PM_Bay_08_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_08/PM_Bay_08_04.csv', 'PM_Bay_08_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_09/PM_Bay_09_01.csv', 'PM_Bay_09_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_09/PM_Bay_09_02.csv', 'PM_Bay_09_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_09/PM_Bay_09_03.csv', 'PM_Bay_09_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_09/PM_Bay_09_04.csv', 'PM_Bay_09_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_10/PM_Bay_10_01.csv', 'PM_Bay_10_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_10/PM_Bay_10_02.csv', 'PM_Bay_10_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_10/PM_Bay_10_03.csv', 'PM_Bay_10_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_10/PM_Bay_10_04.csv', 'PM_Bay_10_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_11/PM_Bay_11_01.csv', 'PM_Bay_11_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_11/PM_Bay_11_02.csv', 'PM_Bay_11_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_11/PM_Bay_11_03.csv', 'PM_Bay_11_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_11/PM_Bay_11_04.csv', 'PM_Bay_11_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_12/PM_Bay_12_01.csv', 'PM_Bay_12_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_12/PM_Bay_12_02.csv', 'PM_Bay_12_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_12/PM_Bay_12_03.csv', 'PM_Bay_12_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_12/PM_Bay_12_04.csv', 'PM_Bay_12_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_13/PM_Bay_13_01.csv', 'PM_Bay_13_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_13/PM_Bay_13_02.csv', 'PM_Bay_13_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_13/PM_Bay_13_03.csv', 'PM_Bay_13_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_13/PM_Bay_13_04.csv', 'PM_Bay_13_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_14/PM_Bay_14_01.csv', 'PM_Bay_14_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_14/PM_Bay_14_02.csv', 'PM_Bay_14_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_14/PM_Bay_14_03.csv', 'PM_Bay_14_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_14/PM_Bay_14_04.csv', 'PM_Bay_14_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_15/PM_Bay_15_01.csv', 'PM_Bay_15_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_15/PM_Bay_15_02.csv', 'PM_Bay_15_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_15/PM_Bay_15_03.csv', 'PM_Bay_15_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_15/PM_Bay_15_04.csv', 'PM_Bay_15_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_16/PM_Bay_16_01.csv', 'PM_Bay_16_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_16/PM_Bay_16_02.csv', 'PM_Bay_16_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_16/PM_Bay_16_03.csv', 'PM_Bay_16_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_16/PM_Bay_16_04.csv', 'PM_Bay_16_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_17/PM_Bay_17_01.csv', 'PM_Bay_17_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_17/PM_Bay_17_02.csv', 'PM_Bay_17_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_17/PM_Bay_17_03.csv', 'PM_Bay_17_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_17/PM_Bay_17_04.csv', 'PM_Bay_17_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_18/PM_Bay_18_01.csv', 'PM_Bay_18_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_18/PM_Bay_18_02.csv', 'PM_Bay_18_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_18/PM_Bay_18_03.csv', 'PM_Bay_18_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_18/PM_Bay_18_04.csv', 'PM_Bay_18_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_19/PM_Bay_19_01.csv', 'PM_Bay_19_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_19/PM_Bay_19_02.csv', 'PM_Bay_19_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_19/PM_Bay_19_03.csv', 'PM_Bay_19_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_19/PM_Bay_19_04.csv', 'PM_Bay_19_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_20/PM_Bay_20_01.csv', 'PM_Bay_20_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_20/PM_Bay_20_02.csv', 'PM_Bay_20_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_20/PM_Bay_20_03.csv', 'PM_Bay_20_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_20/PM_Bay_20_04.csv', 'PM_Bay_20_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_21/PM_Bay_21_01.csv', 'PM_Bay_21_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_21/PM_Bay_21_02.csv', 'PM_Bay_21_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_21/PM_Bay_21_03.csv', 'PM_Bay_21_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_21/PM_Bay_21_04.csv', 'PM_Bay_21_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_22/PM_Bay_22_01.csv', 'PM_Bay_22_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_22/PM_Bay_22_02.csv', 'PM_Bay_22_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_22/PM_Bay_22_03.csv', 'PM_Bay_22_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_22/PM_Bay_22_04.csv', 'PM_Bay_22_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_23/PM_Bay_23_01.csv', 'PM_Bay_23_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_23/PM_Bay_23_02.csv', 'PM_Bay_23_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_23/PM_Bay_23_03.csv', 'PM_Bay_23_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_23/PM_Bay_23_04.csv', 'PM_Bay_23_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_24/PM_Bay_24_01.csv', 'PM_Bay_24_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_24/PM_Bay_24_02.csv', 'PM_Bay_24_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_24/PM_Bay_24_03.csv', 'PM_Bay_24_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_24/PM_Bay_24_04.csv', 'PM_Bay_24_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_25/PM_Bay_25_01.csv', 'PM_Bay_25_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_25/PM_Bay_25_02.csv', 'PM_Bay_25_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_25/PM_Bay_25_03.csv', 'PM_Bay_25_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_25/PM_Bay_25_04.csv', 'PM_Bay_25_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_26/PM_Bay_26_01.csv', 'PM_Bay_26_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_26/PM_Bay_26_02.csv', 'PM_Bay_26_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_26/PM_Bay_26_03.csv', 'PM_Bay_26_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_26/PM_Bay_26_04.csv', 'PM_Bay_26_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_27/PM_Bay_27_01.csv', 'PM_Bay_27_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_27/PM_Bay_27_02.csv', 'PM_Bay_27_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_27/PM_Bay_27_03.csv', 'PM_Bay_27_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_27/PM_Bay_27_04.csv', 'PM_Bay_27_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_28/PM_Bay_28_01.csv', 'PM_Bay_28_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_28/PM_Bay_28_02.csv', 'PM_Bay_28_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_28/PM_Bay_28_03.csv', 'PM_Bay_28_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_28/PM_Bay_28_04.csv', 'PM_Bay_28_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_29/PM_Bay_29_01.csv', 'PM_Bay_29_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_29/PM_Bay_29_02.csv', 'PM_Bay_29_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_29/PM_Bay_29_03.csv', 'PM_Bay_29_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_29/PM_Bay_29_04.csv', 'PM_Bay_29_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_30/PM_Bay_30_01.csv', 'PM_Bay_30_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_30/PM_Bay_30_02.csv', 'PM_Bay_30_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_30/PM_Bay_30_03.csv', 'PM_Bay_30_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_30/PM_Bay_30_04.csv', 'PM_Bay_30_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_31/PM_Bay_31_01.csv', 'PM_Bay_31_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_31/PM_Bay_31_02.csv', 'PM_Bay_31_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_31/PM_Bay_31_03.csv', 'PM_Bay_31_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_31/PM_Bay_31_04.csv', 'PM_Bay_31_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_32/PM_Bay_32_01.csv', 'PM_Bay_32_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_32/PM_Bay_32_02.csv', 'PM_Bay_32_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_32/PM_Bay_32_03.csv', 'PM_Bay_32_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_32/PM_Bay_32_04.csv', 'PM_Bay_32_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_33/PM_Bay_33_01.csv', 'PM_Bay_33_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_33/PM_Bay_33_02.csv', 'PM_Bay_33_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_33/PM_Bay_33_03.csv', 'PM_Bay_33_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_33/PM_Bay_33_04.csv', 'PM_Bay_33_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_34/PM_Bay_34_01.csv', 'PM_Bay_34_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_34/PM_Bay_34_02.csv', 'PM_Bay_34_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_34/PM_Bay_34_03.csv', 'PM_Bay_34_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_34/PM_Bay_34_04.csv', 'PM_Bay_34_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_35/PM_Bay_35_01.csv', 'PM_Bay_35_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_35/PM_Bay_35_02.csv', 'PM_Bay_35_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_35/PM_Bay_35_03.csv', 'PM_Bay_35_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_35/PM_Bay_35_04.csv', 'PM_Bay_35_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_36/PM_Bay_36_01.csv', 'PM_Bay_36_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_36/PM_Bay_36_02.csv', 'PM_Bay_36_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_36/PM_Bay_36_03.csv', 'PM_Bay_36_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_36/PM_Bay_36_04.csv', 'PM_Bay_36_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_37/PM_Bay_37_01.csv', 'PM_Bay_37_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_37/PM_Bay_37_02.csv', 'PM_Bay_37_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_37/PM_Bay_37_03.csv', 'PM_Bay_37_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_37/PM_Bay_37_04.csv', 'PM_Bay_37_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_38/PM_Bay_38_01.csv', 'PM_Bay_38_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_38/PM_Bay_38_02.csv', 'PM_Bay_38_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_38/PM_Bay_38_03.csv', 'PM_Bay_38_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_38/PM_Bay_38_04.csv', 'PM_Bay_38_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_39/PM_Bay_39_01.csv', 'PM_Bay_39_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_39/PM_Bay_39_02.csv', 'PM_Bay_39_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_39/PM_Bay_39_03.csv', 'PM_Bay_39_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_39/PM_Bay_39_04.csv', 'PM_Bay_39_04.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_40/PM_Bay_40_01.csv', 'PM_Bay_40_01.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_40/PM_Bay_40_02.csv', 'PM_Bay_40_02.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_40/PM_Bay_40_03.csv', 'PM_Bay_40_03.csv')
download.file('https://raw.githubusercontent.com/sipbs-compbiol/BM214-Workshop-3/main/assets/data/PM_Bay_40/PM_Bay_40_04.csv', 'PM_Bay_40_04.csv')



library(ggplot2)
library(tidyverse)
```

## Introduction

In this exercise you will use the absorbance data obtained from your yeast growth experiment in Laboratory e to draw growth curves for your three _Saccharomyces cerevisiae_ strains, using the `R` language.

::: { .callout-note collapse="true" }
## Why use `R`?

There are many great tools capable of plotting your data (Numbers, Excel, Prism, GNUplot, Minitab, SPSS, MatLab, Python, JavaScript, etc.) and the choice of tool should in general reflect your data presentation needs, and your level of comfort with the tool.

Here, we use `R` because it is a very powerful means of carrying out many computational aspects of biology, including data visualisation, quickly and easily. Many of the topics you may meet later in your degree - phylogenetic, pharmacokinetics, microbial genomics, and so on - are supported by _packages_ in `R` designed specifically for those subjects, and can make your work much easier. Also, skills in `R` are highly sought-after by industrial and other employers. Having some experience of `R` is an advantage.

`R` may be unfamiliar to you just now, but we provide step-by-step instructions for completing the exercise and, by the end of it, we hope you feel a bit more confident in how to use it.
:::


## Load your data

```{webr-r}
# Load your yeast growth data in this R cell
```